--- 
  backend: 
    branch: master
    name: git-gateway
  collections: 
    - 
      create: true
      fields: 
        - 
          default: blog-post
          label: "Template Key"
          name: templateKey
          widget: hidden
        - 
          label: Title
          name: title
          widget: string
        - 
          label: "Publish Date"
          name: date
          widget: datetime
        - 
          label: Description
          name: description
          widget: text
        - 
          label: Body
          name: body
          widget: markdown
        - 
          label: Tags
          name: tags
          widget: list
      folder: src/pages/blog
      label: Blog
      name: blog
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    - 
      files: 
        - 
          fields: 
            - 
              default: about-page
              label: "Template Key"
              name: templateKey
              widget: hidden
            - 
              label: Title
              name: title
              widget: string
            - 
              label: Body
              name: body
              widget: markdown
          file: src/pages/about/index.md
          label: About
          name: about
        - 
          fields: 
            - 
              default: project-page
              label: "Template Key"
              name: templateKey
              widget: hidden
            - 
              label: Title
              name: title
              widget: string
            - 
              label: Image
              name: image
              widget: image
            - 
              label: Heading
              name: heading
              widget: string
            - 
              label: Description
              name: description
              widget: string
            - 
              fields: 
                - 
                  label: Heading
                  name: heading
                  widget: string
                - 
                  label: Description
                  name: description
                  widget: text
                - 
                  fields: 
                    - 
                      label: Image
                      name: image
                      widget: image
                    - 
                      label: Name
                      name: name
                      widget: string
                    - 
                      label: Text
                      name: text
                      widget: text
                    -
                      label: Links
                      name: links
                      widget: list
                      fields:
                        - 
                          label: "Link Name"
                          name: name
                          widget: string
                        - 
                          label: "Target URL"
                          name: targetURL
                          widget: string
                  label: Projects
                  name: projects
                  widget: list
              label: Intro
              name: intro
              widget: object
            - 
              fields: 
                - 
                  label: Heading
                  name: heading
                  widget: string
                - 
                  label: Description
                  name: description
                  widget: text
                - 
                  fields: 
                    - 
                      label: Image
                      name: image
                      widget: image
                    - 
                      label: Alt
                      name: alt
                      widget: string
                  label: Image1
                  name: image1
                  widget: object
                - 
                  fields: 
                    - 
                      label: Image
                      name: image
                      widget: image
                    - 
                      label: Alt
                      name: alt
                      widget: string
                  label: Image2
                  name: image2
                  widget: object
                - 
                  fields: 
                    - 
                      label: Image
                      name: image
                      widget: image
                    - 
                      label: Alt
                      name: alt
                      widget: string
                  label: Image3
                  name: image3
                  widget: object
              label: Main
              name: main
              widget: object
            - 
              fields: 
                - 
                  label: Quote
                  name: quote
                  widget: string
                - 
                  label: Author
                  name: author
                  widget: string
              label: Testimonials
              name: testimonials
              widget: list
            - 
              label: Full_image
              name: full_image
              widget: image
            - 
              fields: 
                - 
                  label: Heading
                  name: heading
                  widget: string
                - 
                  label: Description
                  name: description
                  widget: string
                - 
                  fields: 
                    - 
                      label: Plan
                      name: plan
                      widget: string
                    - 
                      label: Price
                      name: price
                      widget: string
                    - 
                      label: Description
                      name: description
                      widget: string
                    - 
                      label: Items
                      name: items
                      widget: list
                  label: Plans
                  name: plans
                  widget: list
              label: Pricing
              name: pricing
              widget: object
          file: src/pages/projects/index.md
          label: "Project Portfolio"
          name: projects
      label: Pages
      name: pages
  media_folder: static/img
  public_folder: /img
  